// This file is generated

F_note_0 = [
"",
"<div>\n<i class=\"NoteType\">\nFamily Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n<span style=\"font-size:11px;\">Three children - names not known</span>\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nFamily Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nCheeseman: - John (Jack) - Michael and Derek:<br />\nAfter the death of Tom Cheeseman, his wife Daisy and their two children Michael and Derek went to live with John (Tom's brother) and Maud (Daisy's sister). The children, at around six years old attended a boarding school called 'Royal Russell' (for families of 'Warehousemen, Clerks and Drapers') and would then stay with John and Maud during school holiday's, sometimes travelling down to Shoreham-by-Sea, West Sussex where they would stay with Gilbert and Edith Richards at <a href=\"media.html?mdx=2\">Tipperary 100 Old Fort Road</a>. (Edith was sister to Henry, Tom, John and Kathleen Cheeseman)\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nFamily Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n<span style=\"font-size:11px;\">No children</span>\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nFamily Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n<span style=\"font-size:11px;\">At least one child - thought to be called Peter</span>\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nAssociation Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n<strong></strong><span style=\"font-size:16px;\"><strong></strong></span><span style=\"color:#2e3436;\"><span style=\"font-size:16px;\"><strong>Hilda Sharp, Ian and Laurie </strong></span></span><span style=\"font-size:16px;\"><strong></strong></span><span style=\"color:#3465a4;\"><span style=\"font-size:16px;\"><strong>- </strong></span></span><span style=\"text-decoration:underline;\"><span style=\"color:#3465a4;\"><span style=\"font-size:16px;\"><strong>The Beginnings and to the End</strong></span></span></span><span style=\"color:#3465a4;\"><span style=\"font-size:16px;\"><strong></strong></span></span><span style=\"font-size:16px;\"><strong></strong></span><span style=\"font-size:16px;\"></span>\n</p>\n<p>\n<span style=\"font-size:16px;\">It is strongly believed that Hilda was engaged to be married to Harry Gibbons who was killed in the first world war but Hilda continued to be included in all family gatherings.  In 1947 Hilda was helping Vera Perry nee Gibbons organise a Christmas party being held for Ian and Sheila Perry at Lynwood Drive.</span>\n</p>\n<p>\n<span style=\"font-size:16px;\">In that period it was a more formal practice to have equal numbers of both girl and boy at the party. Vera found that she was one girl short of making up the equal numbers.</span>\n</p>\n<p>\n<span style=\"font-size:16px;\">It was Hilda who suggested asking Laura (Laurie) Cheeseman (whom she new from her association with Henry Cheeseman, her boss) to make up the numbers and as Laurie and Sheila where in the same class at school (WHS) the suggestion made sense.</span>\n</p>\n<p>\n<span style=\"font-size:16px;\">It was to be this party that would be the beginnings of a long and happy relationship between Ian Perry and Laurie Cheeseman.</span>\n</p>\n<p>\n<span style=\"font-size:16px;\">Hilda remained to be a large part of Ian Laurie's life up to her death.</span>\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nFamily Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n<span style=\"font-size:11px;\">No children</span>\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
""
]
Dwr.ScriptLoaded('dwr_db_F_note_0.js');
