// This file is generated

M_note_0 = [
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nLink\n</i>\n<div class=\"grampsstylednote\">\n<p>\n<a href=\"media.html?mdx=22\"></a><a href=\"media.html?mdx=22\"><a href=\"media.html?mdx=22\"></a></a><a href=\"media.html?mdx=22\"><a href=\"media.html?mdx=22\"><a href=\"media.html?mdx=22\">A Guide to better Ventilation from Vent-Axia</a></a></a>\n</p>\n<p>\n<strong></strong><span style=\"font-size:14px;\"><strong></strong></span><span style=\"color:#8f5902;\"><span style=\"font-size:14px;\"><strong>_Click the Link_</strong></span></span><span style=\"font-size:14px;\"><strong></strong></span><strong></strong>\n</p>\n<p>\n&nbsp;\n</p>\n</div>\n</div>",
"",
"",
"<div>\n<i class=\"NoteType\">\nMedia Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nThe Royal Military Academy Sandhurst (RMAS) is where all officers in the British Army are trained to take on the responsibility of leading their soldiers. During training, all officer cadets learn to live by the academy\u2019s motto: \u2018Serve to Lead\u2019\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nMedia Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n&nbsp;\n</p>\n<p>\n<span style=\"font-size:14px;\"><span style=\"color:#8f5902;\"><strong>_CLICK the Link Below the Title to Open the File_</strong></span></span><span style=\"color:#8f5902;\"><strong></strong></span><strong></strong>\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nMedia Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n&nbsp;\n</p>\n<p>\n<span style=\"font-size:14px;\"><span style=\"color:#8f5902;\"><strong>_CLICK the Link Below the Title to Open the File_</strong></span></span><span style=\"color:#8f5902;\"><strong></strong></span><strong></strong>\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nMedia Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n&nbsp;\n</p>\n<p>\n<span style=\"font-size:14px;\"><span style=\"color:#8f5902;\"><strong>_CLICK the Link Below the Title to Open the File_</strong></span></span><span style=\"color:#8f5902;\"><strong></strong></span><strong></strong>\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nMedia Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n<strong>Cadet Company Sergeant Major:</strong><br />\n<strong></strong><a href=\"media.html?mdx=43\">Badge</a>\n</p>\n<p>\nUK - <a href=\"https://www.cadetkitshop.com/pages/cadet-ranks\">Cadet kit shop.com</a>.....<br />\nCadet Company Sergeant Major<br />\nThis is the second highest rank you as a cadet can hope to achieve. This rank places you in charge of the cadets within their respective company\n</p>\n<p>\nUK - <a href=\"https://armycadets.com/news-and-events/features/quick-guide-to-cadet-badges-and-ranks/\">Army Cadets .com</a>....<br />\nRank: Cadet Company Sergeant Major<br />\nRequirements: Must have passed APC 4 star<br />\nResponsibilities: The senior cadet in a Company. Responsible for mentoring senior cadets and taking a Company parade.\n</p>\n<p>\n<a href=\"https://en.wikipedia.org/wiki/Company_sergeant_major\">Wiki</a>....<br />\nThe Company Sergeant Major (CSM) is the senior non-commissioned soldier of a company in the armies of many Commonwealth countries, responsible for administration, standards and discipline. In combat, his prime responsibility is the supply of ammunition to the company.\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nMedia Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nRobinson-Quickenden Wedding 27 Sept 1899 _Haven_ Herne Bay\n</p>\n<p>\nFrom: Erick Scott: 2019 / 2020<br />\nTo: Laura Perry(nee Cheeseman)\n</p>\n<p>\nThe Haven of Laura's wedding to Robert Quickenden in September 1899. Dulcie was there too as a young bridesmaid with her sister Vera on the lawn. Also there were their parents Ernest Jones and Alice Gertrude Jones(nee Robinson, sister to the bride). My great-aunt Ena annotated the photo. Other photos suggest to me she may have mixed Minnie with May. As cousin Brian Brady says, she had been trying to recall after many decades.<br />\nI hope the attached listing written for cousin Maureen Brady(neeWest) by her mother, my great aunt Ena West(neeJohnson) will make it clear(but I notice on the Marriage Certificate that the Reverend was really Thomas Watkins not Watson).\n</p>\n<p>\nBy: Ena West(nee Johnson)<br />\nFor: Maureen Brady\n</p>\n<p>\nPicture of Wedding group (Quickendens &amp; her husband uncle Robert Quickenden) was taken on 27 Sept 1899 in the Haven garden (before Haven was altered with extra bedrooms added on at back)<br />\nPeople from left to right in group (grandpa William Johnson, your great grandpa Johnson) Uncle Ernest Jones &amp; Auntie Alice (Dulcie's mother and farther). The bearded gentleman in silk hat in back row was a mr. Pearce whose wife is next to the bride-groom his 4 daughters are the bride's maids on the left of bridegroom (Auntie Laura married a widower &amp; these people were his 1st wifes relatives).<br />\nClergyman Rev: Watkins married them (I can still remember him for he was a vicar at St John's Herne Bay for many years) the gentleman with side wiskers, head between bride-groom &amp; bride, was probabley bridegroom's father or uncle who was a former Quickenden. Next gentleman (with beard) &amp; lady was grandpa &amp; grandma Robert Robinson (Aunite Laura's Dulcie Alice Earnest my mother's, mothers father) the next gentleman, dark ..?.. the 3 brides-maids are Auntie Emm auntie May, aunite Minnie Uncle Charles (Sally's father Charles &amp; mother May) &amp; then my mother &amp; father your grandma &amp; grandpa George Johnson.<br />\nThe little brides maids are (sisters) vera &amp; auntie Dulcie Jones then to be wife to mr Henry (Harry) Cheeseman, Lauries mother. I still have auntie Laura's wedding dress &amp; veil, I tried to find it for your wedding ( have found it since, rather yellowed\n</p>\n<p>\nNB:<br />\nThank you Erick for this valuable information / contribution !!\n</p>\n<p>\n&nbsp;\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nMedia Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n&nbsp;\n</p>\n<p>\n<span style=\"font-size:14px;\"><span style=\"color:#8f5902;\"><strong>_CLICK the Link Below the Title to Open the File_</strong></span></span><span style=\"color:#8f5902;\"><strong></strong></span><strong></strong>\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nMedia Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n&nbsp;\n</p>\n<p>\n<span style=\"font-size:14px;\"><span style=\"color:#8f5902;\"><strong>_CLICK the Link Below the Title to Open the File_</strong></span></span><span style=\"color:#8f5902;\"><strong></strong></span><strong></strong>\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nEvent Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n&nbsp;\n</p>\n<p>\n<strong>Ian Perry - Life Assurance - A more detailed insight:</strong>\n</p>\n<p>\n&nbsp;\n</p>\n<p>\n<span style=\"color:#555753;\">Don't won't to read - Click the above Link to Play the Audio transcript :)</span>\n</p>\n<p>\n&nbsp;\n</p>\n<p>\nFist of all I would like to give a very brief introduction to Sir Mark Aubrey Weinberg. (As you read on you may begin to see the significance of bringing this man to your attention).\n</p>\n<p>\n&nbsp;\n</p>\n<p>\n[1] Sir Mark Weinberg, Mark One: senior statesman of the life assurance industry, who, with his three companies - Abbey Life, Hambro Life and Allied Dunbar - was closely identified with ushering in hard-sell and aggressive marketing techniques. Mark One is rich and ambitious, working with his close friend, Jacob Rothschild to make even more money from their latest business venture - J Rothschild Assurance. Then there is Weinberg, Mark Two - in many ways, a more interesting figure. This is the campaigner urging companies to donate a proportion of their profits to charity, a tireless worker for good causes, a large personal charitable donor.\n</p>\n<p>\n&nbsp;\n</p>\n<p>\n(If like me, you can\u2019t help yourself from wanting to understand a little more about the man behind the assurance companies that Ian Perry was immersed in for ten years, then I encourage you to learn a little more about this man here..  <a href=\"https://www.managementtoday.co.uk/uk-profile-sir-mark-weinberg/article/409526\">management today .co.uk</a>  ...and it will also reveal his link to the colourful world of film \u2013 think 007).\n</p>\n<p>\n&nbsp;\n</p>\n<p>\n[2] In 1961, Mark Weinberg founded Abbey Life Assurance Company in London, which was one of the first companies to develop unit-linked assurance and where he formed one of the UK\u2019s first retail property funds.\n</p>\n<p>\n&nbsp;\n</p>\n<p>\nIn 1971, he went on to found Hambro Life Assurance, (subsequently called Allied Dunbar) It was first listed on the London Stock Exchange in 1975. The company expanded its financial adviser operations during the late '70s and early '80s, acquiring the Allied Unit Trusts of which it was soon the major unitholder, to become 'Allied Hambro' in 1984. At Allied Dunbar, he was managing director until 1983 (it is now part of Zurich Financial Services), operating in the insurance broker market as well as building up a sales force. There he formed the first retail managed fund and originated the concept of the variable premium whole life policy.\n</p>\n<p>\n&nbsp;\n</p>\n<p>\nSo now we have learnt a little about who Sir Mark Weinberg is and the companies that he founded. For those of you that have known Ian Perry, I expect you can now see where Sir Mark Weinberg falls in to place in Ian\u2019s career as a representative for various Life Assurance Companies. Now follows my best account of Ian\u2019s time working in the world of life assurance.\n</p>\n<p>\n&nbsp;\n</p>\n<p>\nI believe that Ian had his first employment in life assurance with Abbey Life Assurance Company and then, due to Ian\u2019s administrative abilities and expertise with recruiting, training and the motivation of sales staff and out-standing personal qualities he was asked to join Hambo Life Assurance as one it\u2019s first members soon after Mark Weinberg founded it in 1971.\n</p>\n<p>\n&nbsp;\n</p>\n<p>\nIn the years ahead Ian was a branch manager (Soke-On-Trent) with staff totalling, 2 administrators, 1 field supervisor and 16 Sales Associates. Although the hours where long, Ian loved his work and had built up a reputation for honest ethical conduct that was second to none and can be verified by letters written to Ian by key people within firms and bank, expressing great appreciation and satisfaction for his work ethics and help. \n</p>\n<p>\n&nbsp;\n</p>\n<p>\nIan\u2019s work and success as branch manager had also made a significant impression on his bosses. So much so, that Ian was asked to give a talk (that would last for a half hour) at the companies 1973 sales conference held in Istanbul. However, in the mid 1970\u2019s the company policies where to change which where to force Ian\u2019s hand in giving in his resignation.\n</p>\n<p>\n&nbsp;\n</p>\n<p>\nWeinberg\u2019s hard-sell and aggressive marketing techniques was about to be unleashed on to the branch managers \u2013 It\u2019s to be a numbers game from here on. This would bring further success for Weinberg and his company but these new tactics was a call too far for Ian to bring to bear. These tactics stood for everything that Ian was not, professionally, personally and morally. He could see no other choice and would have to resign from his position as branch manager. (From the perspective of a family man and husband, his decision and consequence would be deeply felt.)\n</p>\n<p>\n&nbsp;\n</p>\n<p>\nIt would seem that these same tactics that Mark Weinberg deployed in his company would go on to be common place through out the industry \u2013 [1] His methods - pushy advertising, hard-selling, paying high commission to agents sending him business and introducing new unit-linked products - were frowned upon by many.\n</p>\n<p>\n&nbsp;\n</p>\n<p>\nIan\u2019s foresight into the way life assurance would be sold into the future led him to not only leave Hambro Life but also to leave (with some sadness) the Life Assurance industry altogether.\n</p>\n<p>\n&nbsp;\n</p>\n<p>\nSource [1]: management today:<br />\n<a href=\"https://www.managementtoday.co.uk/uk-profile-sir-mark-weinberg/article/409526\">https://www.managementtoday.co.uk/uk-profile-sir-mark-weinberg/article/409526</a>\n</p>\n<p>\n&nbsp;\n</p>\n<p>\nSource [2]: Wikipedia:<br />\n<a href=\"https://en.wikipedia.org/wiki/Mark_Weinberg \">https://en.wikipedia.org/wiki/Mark_Weinberg </a><br />\n<a href=\"https://en.wikipedia.org/wiki/Allied_Dunbar#cite_note-mark1\">https://en.wikipedia.org/wiki/Allied_Dunbar#cite_note-mark1</a><br />\n<a href=\"https://en.wikipedia.org/wiki/Abbey_Life \">https://en.wikipedia.org/wiki/Abbey_Life </a>\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nMedia Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nHenry (Harry) Cheeseman, Auctioneer, Surveyor and Estate Agent - Partner to John Hollingsworth (in photo)\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nMedia Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n&nbsp;\n</p>\n<p>\n<span style=\"font-size:14px;\"><span style=\"color:#8f5902;\"><strong>_CLICK the Link Below the Title to Open the File_</strong></span></span><span style=\"color:#8f5902;\"><strong></strong></span><strong></strong>\n</p>\n</div>\n<i class=\"NoteType\">\nHtml code\n</i>\n<div class=\"grampsstylednote\">\n<strong>King's College School</strong>, commonly referred to as <strong>KCS</strong>, King's or KCS Wimbledon, is a selective independent school in Wimbledon, southwest London, England. The school was founded in 1829 as the junior department of King's College London and had part of the school\u2019s premises in Strand, prior to relocating to Wimbledon in 1897.<br/><iframe src=\"https://www.google.com/maps/embed?pb=!4v1589751620495!6m8!1m7!1sEdCjnnA1FDt2MaPfGudfoA!2m2!1d51.4216364345824!2d-0.2266251446650424!3f114.50336409105053!4f-0.4887877843935229!5f1.9587109090973311\" width=\"600\" height=\"450\" frameborder=\"0\" style=\"border:0;\" allowfullscreen=\"\" aria-hidden=\"false\" tabindex=\"0\"></iframe>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nGeneral\n</i>\n<div class=\"grampsstylednote\">\n<p>\nDerek and his brother Michael spent some of their school holiday's at Tipperary\n</p>\n<p>\n<a href=\"media.html?mdx=2\">Tipperary 100 Old Fort Road, Shoreham-by-Sea</a>\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nMedia Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n&nbsp;\n</p>\n<p>\n<span style=\"font-size:14px;\"><span style=\"color:#8f5902;\"><strong>_CLICK the Link Below the Title to Open the File_</strong></span></span><span style=\"color:#8f5902;\"><strong></strong></span><strong></strong>\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nMedia Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n&nbsp;\n</p>\n<p>\n<span style=\"font-size:14px;\"><span style=\"color:#8f5902;\"><strong>_CLICK the Link Below the Title to Open the File_</strong></span></span><span style=\"color:#8f5902;\"><strong></strong></span><strong></strong>\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nMedia Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nVictoria Street:<br />\nA study of Victoria Street around the period (1881 Census) that Ann Gibbons and her son Thomas Charles where residing at Grosvenor Mansions. The pdf files include a guided walk with map and audio..\n</p>\n</div>\n</div>",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nMedia Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nWedding of Henry L Cheeseman and Dulcie S M Jones\n</p>\n<p>\nIt is a strong assumption of Laura Cheeseman (daughter to Henry and Dulcie) that the man standing to the left of Henry is his business partner John Hollingsworth and most likely his best man for the day. Sadly, Dulcie's farther had passed away and so Dulcie's cousin George Johnson (standing to Dulcie's right) gave Dulcie away.\n</p>\n<p>\nStanding from left - Thomas Cheeseman, probably John Hollingsworth (best man) Henry L Cheeseman (Bridegroom) and Dulcie S M Cheeseman nee Jone (Bridesmaid), George Johnson, Laura Quickenden nee Robinson, Sally Robison (bridesmaid). Seated from left - Rebecca Cheeseman nee Page, Nora Richards (bridesmaid), next bridesmaid ?, Emmeline Robinson on the end\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nMedia Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n&nbsp;\n</p>\n<p>\n<span style=\"font-size:14px;\"><span style=\"color:#8f5902;\"><strong>_CLICK the Link Below the Title to Open the File_</strong></span></span><span style=\"color:#8f5902;\"><strong></strong></span><strong></strong>\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nMedia Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n&nbsp;\n</p>\n<p>\n<span style=\"font-size:14px;\"><span style=\"color:#8f5902;\"><strong>_CLICK the Link Below the Title to Open the File_</strong></span></span><span style=\"color:#8f5902;\"><strong></strong></span><strong></strong>\n</p>\n</div>\n</div>",
"",
""
]
Dwr.ScriptLoaded('dwr_db_M_note_0.js');
