// This file is generated

I_note_0 = [
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n<span style=\"font-size:14px;\">Laurie (Laura Perry nee Cheeseman), remembers Jane as grandma Gibbons and recalls her as a small, kind and gentle person.</span>\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n<span style=\"font-size:16px;\">Herbert Bridge:</span><br />\n<span style=\"font-size:16px;\">It's possible that his Father and Mother and brother's and sisters are the following...</span>\n</p>\n<p>\n<span style=\"font-size:16px;\">W:\\My Documents\\Family Archive - Docs\\Find My Past</span><br />\n<span style=\"font-size:16px;\"></span><em><span style=\"font-size:16px;\"></span></em><span style=\"color:#ad7fa8;\"><em><span style=\"font-size:16px;\">Herbert Bridge and Family_Record Transcription_ 1891 England, Wales &amp; Scotland Census _ findmypast.co.uk.pdf</span></em></span><em><span style=\"font-size:16px;\"></span></em><span style=\"font-size:16px;\"></span><br />\n<span style=\"font-size:16px;\">1891 England, Wales &amp; Scotland Census</span><br />\n<span style=\"font-size:16px;\">Spring Vale Terrace, Hammersmith, Fulham, London &amp; Middlesex, England</span>\n</p>\n<p>\n<span style=\"font-size:16px;\">W:\\My Documents\\Family Archive - Docs\\Find My Past</span><br />\n<span style=\"font-size:16px;\"></span><em><span style=\"font-size:16px;\"></span></em><span style=\"color:#ad7fa8;\"><em><span style=\"font-size:16px;\">Herbert Bridge and Family-2_Record Transcription_ 1901 England, Wales &amp; Scotland Census _ findmypast.co.uk.pdf</span></em></span><em><span style=\"font-size:16px;\"></span></em><span style=\"font-size:16px;\"></span><br />\n<span style=\"font-size:16px;\">1901 England, Wales &amp; Scotland Census</span><br />\n<span style=\"font-size:16px;\">5, Lawn Terrace, Fulham, London &amp; Middlesex, England</span>\n</p>\n<p>\n<span style=\"font-size:16px;\">W:\\My Documents\\Family Archive - Docs\\Find My Past</span><br />\n<span style=\"font-size:16px;\"></span><em><span style=\"font-size:16px;\"></span></em><span style=\"color:#ad7fa8;\"><em><span style=\"font-size:16px;\">Herbert Bridge and Family-3_Record Transcription_ 1911 Census For England &amp; Wales _ findmypast.co.uk.pdf</span></em></span><em><span style=\"font-size:16px;\"></span></em><span style=\"font-size:16px;\"></span><br />\n<span style=\"font-size:16px;\">1911 Census For England &amp; Wales</span><br />\n<span style=\"font-size:16px;\">86 Chesson Road W Kensington W, Fulham, London &amp; Middlesex, England</span>\n</p>\n<p>\n&nbsp;\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nFamily Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nCheeseman: - John (Jack) - Michael and Derek:<br />\nAfter the death of Tom Cheeseman, his wife Daisy and their two children Michael and Derek went to live with John (Tom's brother) and Maud (Daisy's sister). The children, at around six years old attended a boarding school called 'Royal Russell' (for families of 'Warehousemen, Clerks and Drapers') and would then stay with John and Maud during school holiday's, sometimes travelling down to Shoreham-by-Sea, West Sussex where they would stay with Gilbert and Edith Richards at <a href=\"media.html?mdx=2\">Tipperary 100 Old Fort Road</a>. (Edith was sister to Henry, Tom, John and Kathleen Cheeseman)\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nHenry (Harry) Leslie Cheeseman:\n</p>\n<p>\nIn the period before the National Health Service and in the event of the death of Henry's father, William Stookley, Henry (the eldest son) would contribute his earnings to the family house hold income.\n</p>\n<p>\nIn August of 1959 Henry, a long established member of the Freemasons, would achieve the honour of <a href=\"media.html?mdx=75\"></a><a href=\"media.html\"><a href=\"media.html?mdx=75\">'London Grand Chapter Rank'.</a></a><a href=\"media.html?mdx=75\"></a> \n</p>\n<p>\nIt is evident from letters received by Laura (Henry's daughter) following Henry's death that he was a well regarded, strait thinking, kind gentleman and even the regional director of <a href=\"media.html?mdx=95\"></a><a href=\"media.html\"><a href=\"media.html?mdx=95\">Midland Bank LTD wrote to Henry upon his retirement</a></a><a href=\"media.html?mdx=95\"></a> and his move to live in Prestbury, wishing to record their pride and satisfaction for having been his banker for almost 60 years.\n</p>\n</div>\n</div>",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nKathleen (Kitto) Cheeseman:<br />\nKitto's career started out as a Sales assistance at Dickens &amp; Jones and also Swan &amp; Edgars in Regent Street London and later on she would have her own dress shop in St' Georges Road Wimbledon. After her sister-in-law ( Dulcie Cheeseman, wife to Henry) died, Kitto and Rebecca (mother to Henry and Kitto) moved in to Henry's home and sometime later Kitto would give up her dress shop to help look after Henry's daughter Laura and her mother Rebecca.\n</p>\n<p>\nAll though Laura had lost her mother at an early age, Laura recalls feeling very comfortable in Kitto's company, which is evident in the many photo's of them together.\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nFamily Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nCheeseman: - John (Jack) - Michael and Derek:<br />\nAfter the death of Tom Cheeseman, his wife Daisy and their two children Michael and Derek went to live with John (Tom's brother) and Maud (Daisy's sister). The children, at around six years old attended a boarding school called 'Royal Russell' (for families of 'Warehousemen, Clerks and Drapers') and would then stay with John and Maud during school holiday's, sometimes travelling down to Shoreham-by-Sea, West Sussex where they would stay with Gilbert and Edith Richards at <a href=\"media.html?mdx=2\">Tipperary 100 Old Fort Road</a>. (Edith was sister to Henry, Tom, John and Kathleen Cheeseman)\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nForeman at Wall Plate Manufacture<br />\n--<br />\nDied before 27 August 1876 - the year of his sons marriage\n</p>\n</div>\n</div>",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n<span style=\"font-size:16px;\">William Stookley:</span><br />\n<span style=\"font-size:16px;\">was first a grocer by trade and then a House and Estate Agent, but also he was a Lay preacher. ( We know that he was a partaker of the holy communion at the Holy Trinity Church, Upper Tooting, London. It was thought that he preached at the Holy Trinity Church however there is a note book that is believed to belong to William Stookely which has a hand written sermon giving reference to the Upper Tooting Methodist Church. As at this date May 2019 we have no firm evidence to where William did preach.)</span>\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nMrs Flood not only helped Laurie with some family tasks she in-fact was just like having a caring Mum/Grandma around the home, loved by all.\n</p>\n</div>\n</div>",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nNellie, was not just a domestic worker for Laurie. She also came out on the occasional days outing with Laurie, her father and kids, notably Southport and Dove Dale.\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n<span style=\"font-size:11px;\">Harry Gibbons: Not sure that this is his First name. It's possible that Harold is the first name however Laurie (Laura Perry nee Cheeseman) believes she recalls Hilda Sharp being engaged to a Harry Gibbons who died in the WW1.</span>\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n<span style=\"font-size:11px;\">Winifred:</span><br />\n<span style=\"font-size:11px;\">Laura Perry nee Cheeseman recalls Winifred as being very kind and gentle. She came to stay at Laura's home in Prestbury when Laura had just given birth to Bryan. She would also have a very calming effect on Herbert Bridge (her husband) who was a powerful but gentle man. The name Herbert was given to Bryan as his middle name.</span><span style=\"font-size:16px;\"></span>\n</p>\n<p>\n&nbsp;\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n<span style=\"font-size:11px;\">Elsie M Hollad:</span><br />\n<span style=\"font-size:11px;\">As at to date 3rd June 2019 no record found that can be conclusively associated to Elsie M Holland.</span>\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n<span style=\"font-size:11px;\">George Chalonor Johnson:</span><br />\n<span style=\"font-size:11px;\">As Ernest Jones had died George Jonson gave away Dulcie Jones to Henry Cheeseman</span>\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n<span style=\"font-size:11px;\">George Francis Chaloner:</span><br />\n<span style=\"font-size:11px;\">Possibly died in 1908 - British Army Service Records - 9th Battalion (Queen Victoria's)..</span><br />\n<span style=\"font-size:11px;\">Or did he have a second wife as believed by Nigel Richards</span>\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nTaken from the 1881 England Census database,\n</p>\n<p>\nHenry A. Page state of marriage is Widow.\n</p>\n<p>\nHis relationship to the head-of-household of 41, Abbey Street, Faversham, Kent is Lodger.\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nGeneral\n</i>\n<div class=\"grampsstylednote\">\n<p>\nRymans name in the Richards family:\n</p>\n<p>\nIt was thought by Derick Cheeseman that the name Ryman that appeared in the Richards family was due to a connection with the man Henry J Ryman, the founder of Ryman, who opened his first store and the first ever self-service stationery shop in London at Great Portland Street in 1893. However, my research has found little evidence to support this.\n</p>\n<p>\nMy research shows that the name Ryman began to appear during the marriage of William Emmanuel Richards and Thurza Hannah Earl. Between them they had ten children of which six would have the name Ryman in their name with the first appearance going to the third child, Gilbert (born, year 1876).\n</p>\n<p>\nWilliam Emmanuel Richards and Henry John Ryman where born just three years apart but relatively speaking for that period they lived miles apart. William born in 1849 and residing in Oxford and Henry born in 1852 and residing in London.\n</p>\n<p>\nNeither William Richards or Thurza Earl have a parent with the name Ryman.\n</p>\n<p>\nHowever, William Emmanuel Richards occupation as stated in the 1881 Cencus was Printseller Publisher &amp; Carver &amp; Gilder. Could this occupation be a link?\n</p>\n<p>\nAccording to the 1901 census, Gilbert Ryman Richards (born 1876) was residing in St George Hanover Square, London and his occupation was Gunmakers Clerk and then in 1911 and residing at 238 Worple Road Wimbledon, London his occupation was Commercial Traveller Fine Cu Printers And Fancy Goods - could Gilbert be working for Henry J Ryman ? If so, could this be the reason why the Ryman name had been associated with the Richards name ? \n</p>\n<p>\nFor me and for the time being, the reason why the name Ryman came in to being in the Richards family, is unresolved - Do you know something about this?\n</p>\n<p>\nLINKS:<br />\nhttps://www.geni.com/people/Henry-Ryman/6000000039001135655\n</p>\n<p>\nhttps://www.ryman.co.uk/history-of-ryman\n</p>\n<p>\nhttps://en.wikipedia.org/wiki/Ryman\n</p>\n<p>\n&nbsp;\n</p>\n</div>\n</div>",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nGeneral\n</i>\n<div class=\"grampsstylednote\">\n<p>\nRymans name in the Richards family:\n</p>\n<p>\nIt was thought by Derick Cheeseman that the name Ryman that appeared in the Richards family was due to a connection with the man Henry J Ryman, the founder of Ryman, who opened his first store and the first ever self-service stationery shop in London at Great Portland Street in 1893. However, my research has found little evidence to support this.\n</p>\n<p>\nMy research shows that the name Ryman began to appear during the marriage of William Emmanuel Richards and Thurza Hannah Earl. Between them they had ten children of which six would have the name Ryman in their name with the first appearance going to the third child, Gilbert (born, year 1876).\n</p>\n<p>\nWilliam Emmanuel Richards and Henry John Ryman where born just three years apart but relatively speaking for that period they lived miles apart. William born in 1849 and residing in Oxford and Henry born in 1852 and residing in London.\n</p>\n<p>\nNeither William Richards or Thurza Earl have a parent with the name Ryman.\n</p>\n<p>\nHowever, William Emmanuel Richards occupation as stated in the 1881 Cencus was Printseller Publisher &amp; Carver &amp; Gilder. Could this occupation be a link?\n</p>\n<p>\nAccording to the 1901 census, Gilbert Ryman Richards (born 1876) was residing in St George Hanover Square, London and his occupation was Gunmakers Clerk and then in 1911 and residing at 238 Worple Road Wimbledon, London his occupation was Commercial Traveller Fine Cu Printers And Fancy Goods - could Gilbert be working for Henry J Ryman ? If so, could this be the reason why the Ryman name had been associated with the Richards name ? \n</p>\n<p>\nFor me and for the time being, the reason why the name Ryman came in to being in the Richards family, is unresolved - Do you know something about this?\n</p>\n<p>\nLINKS:<br />\nhttps://www.geni.com/people/Henry-Ryman/6000000039001135655\n</p>\n<p>\nhttps://www.ryman.co.uk/history-of-ryman\n</p>\n<p>\nhttps://en.wikipedia.org/wiki/Ryman\n</p>\n<p>\n&nbsp;\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nGeneral\n</i>\n<div class=\"grampsstylednote\">\n<p>\nRymans name in the Richards family:\n</p>\n<p>\nIt was thought by Derick Cheeseman that the name Ryman that appeared in the Richards family was due to a connection with the man Henry J Ryman, the founder of Ryman, who opened his first store and the first ever self-service stationery shop in London at Great Portland Street in 1893. However, my research has found little evidence to support this.\n</p>\n<p>\nMy research shows that the name Ryman began to appear during the marriage of William Emmanuel Richards and Thurza Hannah Earl. Between them they had ten children of which six would have the name Ryman in their name with the first appearance going to the third child, Gilbert (born, year 1876).\n</p>\n<p>\nWilliam Emmanuel Richards and Henry John Ryman where born just three years apart but relatively speaking for that period they lived miles apart. William born in 1849 and residing in Oxford and Henry born in 1852 and residing in London.\n</p>\n<p>\nNeither William Richards or Thurza Earl have a parent with the name Ryman.\n</p>\n<p>\nHowever, William Emmanuel Richards occupation as stated in the 1881 Cencus was Printseller Publisher &amp; Carver &amp; Gilder. Could this occupation be a link?\n</p>\n<p>\nAccording to the 1901 census, Gilbert Ryman Richards (born 1876) was residing in St George Hanover Square, London and his occupation was Gunmakers Clerk and then in 1911 and residing at 238 Worple Road Wimbledon, London his occupation was Commercial Traveller Fine Cu Printers And Fancy Goods - could Gilbert be working for Henry J Ryman ? If so, could this be the reason why the Ryman name had been associated with the Richards name ? \n</p>\n<p>\nFor me and for the time being, the reason why the name Ryman came in to being in the Richards family, is unresolved - Do you know something about this?\n</p>\n<p>\nLINKS:<br />\nhttps://www.geni.com/people/Henry-Ryman/6000000039001135655\n</p>\n<p>\nhttps://www.ryman.co.uk/history-of-ryman\n</p>\n<p>\nhttps://en.wikipedia.org/wiki/Ryman\n</p>\n<p>\n&nbsp;\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nGeneral\n</i>\n<div class=\"grampsstylednote\">\n<p>\nRymans name in the Richards family:\n</p>\n<p>\nIt was thought by Derick Cheeseman that the name Ryman that appeared in the Richards family was due to a connection with the man Henry J Ryman, the founder of Ryman, who opened his first store and the first ever self-service stationery shop in London at Great Portland Street in 1893. However, my research has found little evidence to support this.\n</p>\n<p>\nMy research shows that the name Ryman began to appear during the marriage of William Emmanuel Richards and Thurza Hannah Earl. Between them they had ten children of which six would have the name Ryman in their name with the first appearance going to the third child, Gilbert (born, year 1876).\n</p>\n<p>\nWilliam Emmanuel Richards and Henry John Ryman where born just three years apart but relatively speaking for that period they lived miles apart. William born in 1849 and residing in Oxford and Henry born in 1852 and residing in London.\n</p>\n<p>\nNeither William Richards or Thurza Earl have a parent with the name Ryman.\n</p>\n<p>\nHowever, William Emmanuel Richards occupation as stated in the 1881 Cencus was Printseller Publisher &amp; Carver &amp; Gilder. Could this occupation be a link?\n</p>\n<p>\nAccording to the 1901 census, Gilbert Ryman Richards (born 1876) was residing in St George Hanover Square, London and his occupation was Gunmakers Clerk and then in 1911 and residing at 238 Worple Road Wimbledon, London his occupation was Commercial Traveller Fine Cu Printers And Fancy Goods - could Gilbert be working for Henry J Ryman ? If so, could this be the reason why the Ryman name had been associated with the Richards name ? \n</p>\n<p>\nFor me and for the time being, the reason why the name Ryman came in to being in the Richards family, is unresolved - Do you know something about this?\n</p>\n<p>\nLINKS:<br />\nhttps://www.geni.com/people/Henry-Ryman/6000000039001135655\n</p>\n<p>\nhttps://www.ryman.co.uk/history-of-ryman\n</p>\n<p>\nhttps://en.wikipedia.org/wiki/Ryman\n</p>\n<p>\n&nbsp;\n</p>\n</div>\n</div>",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nGeneral\n</i>\n<div class=\"grampsstylednote\">\n<p>\nRymans name in the Richards family:\n</p>\n<p>\nIt was thought by Derick Cheeseman that the name Ryman that appeared in the Richards family was due to a connection with the man Henry J Ryman, the founder of Ryman, who opened his first store and the first ever self-service stationery shop in London at Great Portland Street in 1893. However, my research has found little evidence to support this.\n</p>\n<p>\nMy research shows that the name Ryman began to appear during the marriage of William Emmanuel Richards and Thurza Hannah Earl. Between them they had ten children of which six would have the name Ryman in their name with the first appearance going to the third child, Gilbert (born, year 1876).\n</p>\n<p>\nWilliam Emmanuel Richards and Henry John Ryman where born just three years apart but relatively speaking for that period they lived miles apart. William born in 1849 and residing in Oxford and Henry born in 1852 and residing in London.\n</p>\n<p>\nNeither William Richards or Thurza Earl have a parent with the name Ryman.\n</p>\n<p>\nHowever, William Emmanuel Richards occupation as stated in the 1881 Cencus was Printseller Publisher &amp; Carver &amp; Gilder. Could this occupation be a link?\n</p>\n<p>\nAccording to the 1901 census, Gilbert Ryman Richards (born 1876) was residing in St George Hanover Square, London and his occupation was Gunmakers Clerk and then in 1911 and residing at 238 Worple Road Wimbledon, London his occupation was Commercial Traveller Fine Cu Printers And Fancy Goods - could Gilbert be working for Henry J Ryman ? If so, could this be the reason why the Ryman name had been associated with the Richards name ? \n</p>\n<p>\nFor me and for the time being, the reason why the name Ryman came in to being in the Richards family, is unresolved - Do you know something about this?\n</p>\n<p>\nLINKS:<br />\nhttps://www.geni.com/people/Henry-Ryman/6000000039001135655\n</p>\n<p>\nhttps://www.ryman.co.uk/history-of-ryman\n</p>\n<p>\nhttps://en.wikipedia.org/wiki/Ryman\n</p>\n<p>\n&nbsp;\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nGeneral\n</i>\n<div class=\"grampsstylednote\">\n<p>\nRymans name in the Richards family:\n</p>\n<p>\nIt was thought by Derick Cheeseman that the name Ryman that appeared in the Richards family was due to a connection with the man Henry J Ryman, the founder of Ryman, who opened his first store and the first ever self-service stationery shop in London at Great Portland Street in 1893. However, my research has found little evidence to support this.\n</p>\n<p>\nMy research shows that the name Ryman began to appear during the marriage of William Emmanuel Richards and Thurza Hannah Earl. Between them they had ten children of which six would have the name Ryman in their name with the first appearance going to the third child, Gilbert (born, year 1876).\n</p>\n<p>\nWilliam Emmanuel Richards and Henry John Ryman where born just three years apart but relatively speaking for that period they lived miles apart. William born in 1849 and residing in Oxford and Henry born in 1852 and residing in London.\n</p>\n<p>\nNeither William Richards or Thurza Earl have a parent with the name Ryman.\n</p>\n<p>\nHowever, William Emmanuel Richards occupation as stated in the 1881 Cencus was Printseller Publisher &amp; Carver &amp; Gilder. Could this occupation be a link?\n</p>\n<p>\nAccording to the 1901 census, Gilbert Ryman Richards (born 1876) was residing in St George Hanover Square, London and his occupation was Gunmakers Clerk and then in 1911 and residing at 238 Worple Road Wimbledon, London his occupation was Commercial Traveller Fine Cu Printers And Fancy Goods - could Gilbert be working for Henry J Ryman ? If so, could this be the reason why the Ryman name had been associated with the Richards name ? \n</p>\n<p>\nFor me and for the time being, the reason why the name Ryman came in to being in the Richards family, is unresolved - Do you know something about this?\n</p>\n<p>\nLINKS:<br />\nhttps://www.geni.com/people/Henry-Ryman/6000000039001135655\n</p>\n<p>\nhttps://www.ryman.co.uk/history-of-ryman\n</p>\n<p>\nhttps://en.wikipedia.org/wiki/Ryman\n</p>\n<p>\n&nbsp;\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nAssociation Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n<strong></strong><span style=\"font-size:16px;\"><strong></strong></span><span style=\"color:#2e3436;\"><span style=\"font-size:16px;\"><strong>Hilda Sharp, Ian and Laurie </strong></span></span><span style=\"font-size:16px;\"><strong></strong></span><span style=\"color:#3465a4;\"><span style=\"font-size:16px;\"><strong>- </strong></span></span><span style=\"text-decoration:underline;\"><span style=\"color:#3465a4;\"><span style=\"font-size:16px;\"><strong>The Beginnings and to the End</strong></span></span></span><span style=\"color:#3465a4;\"><span style=\"font-size:16px;\"><strong></strong></span></span><span style=\"font-size:16px;\"><strong></strong></span><span style=\"font-size:16px;\"></span>\n</p>\n<p>\n<span style=\"font-size:16px;\">It is strongly believed that Hilda was engaged to be married to Harry Gibbons who was killed in the first world war but Hilda continued to be included in all family gatherings.  In 1947 Hilda was helping Vera Perry nee Gibbons organise a Christmas party being held for Ian and Sheila Perry at Lynwood Drive.</span>\n</p>\n<p>\n<span style=\"font-size:16px;\">In that period it was a more formal practice to have equal numbers of both girl and boy at the party. Vera found that she was one girl short of making up the equal numbers.</span>\n</p>\n<p>\n<span style=\"font-size:16px;\">It was Hilda who suggested asking Laura (Laurie) Cheeseman (whom she new from her association with Henry Cheeseman, her boss) to make up the numbers and as Laurie and Sheila where in the same class at school (WHS) the suggestion made sense.</span>\n</p>\n<p>\n<span style=\"font-size:16px;\">It was to be this party that would be the beginnings of a long and happy relationship between Ian Perry and Laurie Cheeseman.</span>\n</p>\n<p>\n<span style=\"font-size:16px;\">Hilda remained to be a large part of Ian Laurie's life up to her death.</span>\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
""
]
Dwr.ScriptLoaded('dwr_db_I_note_0.js');
